services:
  postgres17:
    image: postgres:17-alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=yuji
      - POSTGRES_PASSWORD=S3cret
